### ISSUE TITLE
Configuration not persisted when using --config

### ISSUE THREAD

**Issue by SeraphimSerapis** [deepch/RTSPtoWeb#107]
Hi all,
I'm using the UniFi Protect Integration for Home Assistant and the Proxy Container -- all seems to go well when manually adding cameras via `config.json` but cameras that are added via the Home Assistant integration seem to fail due to the URL format.

The cameras are added with rtsps URLs like `rtsps://IP:7441/token?enableSrtp` and the URL needs to be changed to `rtsp://IP:7447/token` to make things work -- the port changes to `7447` and the protocal to `rtsp`. I already set `channel_defaults` to `insecure_skip_verify": true` to ensure this is not causing any issues, too.

It would be awesome if new cameras would be either added to config.json (so people can manually edit them) or if there would be support for RTSP (or port and protocol remapping).

Thanks in advance and keep up the great work,
Tim

**Comment by allenporter** [comment]
Hi @SeraphimSerapis -- it seems like we should be able to make the RTSPS cameras work? Can you add more detail to https://github.com/deepch/RTSPtoWeb/issues/82 about why its not working?

Also, on persistence, my impression is that RTSPtoWeb does persist its configuration files normally, but its not working when run in the add-on for some reason. I don't think that is an RTSPtoWeb bug itself, as if you run standalone it seems to persist just fine.

**Comment by allenporter** [comment]
We can track the persistence issue in https://github.com/allenporter/stream-addons/issues/29 though i'm not really sure why its not working.  I don't have a use case for this myself, so i am not actively looking into it, and it could use some debugging help debugging why its not working.

**Comment by SeraphimSerapis** [comment]
I'm not using the addon -- simply running the Docker container like so:
```
  ### RTSP to Web ###
  rtsp:
    container_name: rtsp
    restart: unless-stopped
    network_mode: host
    image: ghcr.io/deepch/rtsptoweb:latest
    volumes:
      - ${DOCKERDIR}/appdata/rtsp/config.json:/config/config.json
```

Added my errors to #82 for more information. Hope the information I provided are useful. Thanks for the swift response @allenporter
