### ISSUE TITLE
Is there an example of config.conf for running https

### ISSUE THREAD

**Issue by ranrinc** [deepch/RTSPtoWeb#131]
Is there an example of config for HTTPS. I'm trying the selfsign and so far it doesn't run. This is my current setup

```
{
  "server": {
    "debug": true,
    "http_debug": false,
    "http_demo": true,
    "http_dir": "web",
    "http_login": "demo",
    "http_password": "demo",
    "http_port": ":8083",
    "https": true,
    "https_auto_tls": false,
    "https_auto_tls_name": "",
    "https_cert": "/docker/certs/server.crt",
    "https_key": "/docker/certs/server.key",
    "https_port": ":443",
    "ice_servers": ["stun:stun.l.google.com:19302"],
    "log_level": "debug",
    "rtsp_port": ":5541",
    "token": {
      "backend": "http://127.0.0.1/test.php"
    },
    "defaults": {
      "audio": true
    }
  },
  "streams": {
    "27aec28e-6181-4753-9acd-0456a75f0289": {
      "channels": {
        "0": {
          "url": "rtmp://171.25.232.10/12d525bc9f014e209c1280bc0d46a87e",
          "debug": false,
          "audio": true
        }
      },
      "name": "111111111"
    }
  }
}
```

docker-compose.yml
```
version: "3.8"
services:
  rtsptoweb:
    image: ghcr.io/deepch/rtsptoweb:latest
    container_name: RTSPtoWeb
    ports:
      - 80:8083
      - 443:443
    volumes:
      - /docker/rtsptoweb/config.json:/config/config.json
    restart: unless-stopped
```
