### ISSUE TITLE
Run RTSP2Web on K8s without network=host (WebRTC)

### ISSUE THREAD

**Issue by bkupidura** [deepch/RTSPtoWeb#179]
Im trying to run RTSP2Web on K8s, obviously i want to avoid `network=host`.

Can we expose possibility to replace WebRTC endpoint IP with RTSPtoWeb? RTSPtoWeb should be able instruct clients that they should "connect" to IP "A" to get WebRTC stream.

In K8s i can create LB service type for multiple UDP ports and pass traffic to RTSP2Web container without issue.
Problem is that RTSP2Web is advertising container IP and not service IP.

Im not sure if this is technicly possible but if we can introduce smth like `webrtc_endpoint_ip` should allow people to run RTSP2Web without `network=host`.

```
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: <routable_LB_IP>
    metallb.universe.tf/loadBalancerIPs: <routable_LB_IP>
  labels:
    app.kubernetes.io/name: rtsp2web
  name: rtsp2web-vip-udp
  namespace: smart-home
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 20000
    protocol: UDP
    targetPort: 20000
    name: u1
  - port: 20001
    protocol: UDP
    targetPort: 20001
    name: u2
  - port: 20002
    protocol: UDP
    targetPort: 20002
    name: u3
```

```
{
  "server": {
    "webrtc_port_min": 20000,
    "webrtc_port_max": 20002
  },
  [...]
}
```
