### ISSUE TITLE
Exposing RTSPWeb dashboard outside

### ISSUE THREAD

**Issue by avico78** [deepch/RTSPtoWeb#269]
What ports should i expose when docker network is none host one?
my use case - use the RTSPWeb dashboard viewing webrtc camera stream.
at current getting error :
```
rtsp2web    | 2022/12/31 11:27:04 Set ICEServers [stun:stun.l.google.com:19302]
rtsp2web    | time="2022-12-31T11:27:34Z" level=error msg="WebRTC Client Offline" call=WritePacket channel=0 func=HTTPAPIServerStreamWebRTC module=http_webrtc stream=camera.front_camera
rtsp2web    | time="2022-12-31T11:27:34Z"

```
I guess it related to close ports which probably required .

docker compose:
```
networks:
  dockers_inframain:
    external: true


services:
  rtsp2web:
    container_name: rtsp2web
    image: ghcr.io/deepch/rtsptoweb:latest 
    networks:
      - dockers_inframain
    # network_mode: host
    ports:
      - 8083:8083
    restart: always
    volumes:
      - ./config.yaml:/config/config.json
    labels:
      traefik.enable: true
      traefik.http.routers.nvr.rule: Host(`nvr.${DOMAINNAME}`)
      traefik.http.routers.nvr.entrypoints: websecure
      traefik.http.services.nvr.loadbalancer.server.port: 8083
      traefik.http.routers.nvr.middlewares: nvr_auth
      traefik.http.middlewares.nvr_auth.basicauth.users: ${TRAEFIK_USER}:${TRAEFIK_PASS}

```
