### ISSUE TITLE
Server immediately shuts down in Kubernetes

### ISSUE THREAD

**Issue by awdm** [deepch/RTSPtoWeb#292]
I'm trying to run the server with Kubernetes, Helm and Minikube, but it immediately receives a `signalterminated`. I don't know where that signal is coming from. When I start the same image in Docker, this doesn't happen.

Here is the pods log:
```
time="2023-02-13T10:40:12Z" level=info msg="Server CORE start" func=main module=main
time="2023-02-13T10:40:12Z" level=info msg="Server RTSP start" call=Start func=RTSPServer module=rtsp_server
time="2023-02-13T10:40:12Z" level=info msg="Server HTTP start" call=Start func=RTSPServer module=http_server
time="2023-02-13T10:40:12Z" level=info msg="Server start success a wait signals" func=main module=main
time="2023-02-13T10:40:39Z" level=info msg="Server receive signalterminated" func=main module=main
time="2023-02-13T10:40:41Z" level=info msg="Server stop working by signal" func=main module=main
```

And here is my values.yaml (I build the image myself since the default image contains the default config which doesn't work):
```
replicaCount: 1

image:
  repository: myregistry/videostream
  pullPolicy: Always
  tag: "rtsptoweb"

imagePullSecrets:
  - name: mysecret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "videostreamuser"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
```
